### ISSUE TITLE
Dice roll random number range

### ISSUE THREAD

**Issue by strombom** [b2developer/MonopolyNEAT#2]
It looks like the dice rolls are numbers in the range from 0 up to and including 6. Shouldn't the smallest dice roll be 1?

https://github.com/b2developer/MonopolyNEAT/blob/dd718ee5a59760e278282f4e13055643b6f5e740/Monopoly/Monopoly/Board.cs#L238

**Comment by b2developer** [comment]
https://softwareengineering.stackexchange.com/questions/296858/inclusive-or-exclusive-upper-bound-in-pseudo-random-number-generators

the upper-bound of the RNG is exclusive, meaning that 7 never actually appears
C# creators did this so you could use the array length as an argument without subtracting 1 
eg. int a = random.gen.Next(0,list.Length)
